### PR TITLE
README.md even more formatting

### PR DESCRIPTION
**Pull request by PaulRomerolegal**
full stops, code and acronym

### CODE REVIEW

**Comment by jl777** [comment]
maybe it is better to be editing more recent project documents? this project is not so actively used now

**Comment by PaulRomerolegal** [comment]
@jl777 That would be great. Would you consider adding me as a collaborator to this repository (SuperNET_API) though as I'd really like to clean up/improve some of the old files anyway? (https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/). Being a collaborator would mean you wouldn't have to merge pull requests for small grammar corrections here. In the meantime I'll start looking for stuff to improve on the other repositories (like chipsln and komodo) though I don't need to be a collaborator on those more important repos.
Thanks James!

**Comment by jl777** [comment]
use the lightning, SuperNET, komodo and chips3 repos, those are the active ones

**Comment by PaulRomerolegal** [comment]
@jl777 Understood. I'll start working on those ASAP. Would you please invite me as a collaborator to this repository though anyway just to make some final corrections so it doesn't feel unfinished? It would mean a lot. 😊

**Pull request merged**
